version: '3.8'

services:
  dev:
    container_name: animals_api_dev
    image: animals-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - animals-api-network
    depends_on:
      - mongo-database
      - mongo-express
      - redis
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

networks:
  animals-api-network:
    driver: bridge
