version: '3.8'

services:
  mongo-database:
    container_name: animals-mongo-db
    image: mongo:latest
    restart: always
    ports:
      - 27018:${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - animals-api-network

networks:
  animals-api-network:
    driver: bridge

volumes:
  mongo-data:
