version: '3.8'

services:
  mongo-express:
    container_name: animals-mongo-express
    image: mongo-express:latest
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=animals-mongo-db
    depends_on:
      - mongo-database
    networks:
      - animals-api-network
    restart: unless-stopped

networks:
  animals-api-network:
    driver: bridge