name: Test and lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
  [workflow_call]

jobs:
  code_analyze:
    uses: ./.github/workflows/codeql-analysis.yml
  test:
    name: 'Run unit tests'
    needs: [code_analyze]
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-latest
    # Define the steps for this job
    steps:
    - uses: actions/checkout@v3
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm ci
    
    - name: 'Run Tests'
      run: npm run test

  # Run the linter to check for code style issues
  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: npm ci

    - name: 'Run Linter'
      run: npm run lint